version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: ./Dockerfile.dev
    image: client
    ports:
      - 3000:3000
    restart: on-failure:3
    volumes:
      - ./client:/app
      - ./types:/app/types
    env_file:
      - .env
    networks:
      - naengmyeon_pong_network

  db:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    restart: on-failure:3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - naengmyeon_pong_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: on-failure:3
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - naengmyeon_pong_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    image: backend
    ports:
      - 3001:3001
    restart: on-failure:3
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./types:/app/types
    env_file:
      - .env
    networks:
      - naengmyeon_pong_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  naengmyeon_pong_network:
    driver: bridge
