version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend
    ports:
      - 3000:3000
    restart: on-failure:3
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - naengmyeon_pong_network

networks:
  naengmyeon_pong_network:
    driver: bridge
